application: evophage
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"

libraries:
- name: jinja2
  version: latest
  
builtins:
- appstats: on

handlers:
- url: /login/?
  script: main.app
  secure: always

- url: /signup/?
  script: main.app
  secure: always

- url: /static
  static_dir: static
  expiration: "1d 0m"
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: "7d 0m"

- url: /.*
  secure: always
  script: main.app